name: Bot CROUS

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download seen file
        uses: actions/download-artifact@v4
        with:
          name: seen
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python botcrous.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Upload seen file
        uses: actions/upload-artifact@v4
        with:
          name: seen
          path: seen.txt